'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{launch,delay}=require('../scripts/cdp.cjs');
test('P12 浏览器真实点击分享入口/续关，模拟分享返回，保存额度与库存且小屏弹窗可点',{timeout:45000},async()=>{
 require('../scripts/build.cjs').build();const b=await launch(),c=b.cdp,s=b.sessionId,e=x=>c.evaluate(x,s);
 async function until(expr){for(let i=0;i<200;i++){if(await e(expr))return;await delay(30);}throw Error(expr+' '+await e('JSON.stringify({modal:__arrowDebug.app.modal,savedError:__arrowDebug.app.savedError,pending:__arrowDebug.app.sharePending,message:__arrowDebug.app.message,log:window.shareLog,share:__arrowDebug.app.share,lives:__arrowDebug.app.session?.lives,reason:__arrowDebug.app.session?.failureReason,state:__arrowDebug.app.session?.state})'));}
 async function click(id){const p=await e(`(()=>{const b=__arrowDebug.view.buttons.find(b=>b.id==='${id}'),r=document.querySelector('canvas').getBoundingClientRect();if(!b)throw Error('missing ${id}');return [r.x+b.x+b.width/2,r.y+b.y+b.height/2]})()`);for(const type of ['mousePressed','mouseReleased'])await c.send('Input.dispatchMouseEvent',{type,x:p[0],y:p[1],button:'left',clickCount:1},s);}
 async function shot(name){const {data}=await c.send('Page.captureScreenshot',{format:'png'},s);fs.writeFileSync('reports/screenshots/'+name+'.png',Buffer.from(data,'base64'));}
 try{
 await c.send('Emulation.setDeviceMetricsOverride',{width:320,height:568,deviceScaleFactor:1,mobile:true},s);await c.send('Page.navigate',{url:b.url+'/?debug'},s);await until('!!window.__arrowDebug');
 await e(`__arrowDebug.app.platform.share=()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));setTimeout(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));},100);}`);
 await click('share');await shot('share-daily');await click('share-start');await until('__arrowDebug.app.inventory.time===15');assert.equal(await e('__arrowDebug.app.inventory.life'),15);assert.equal(await e('__arrowDebug.app.inventory.shuffle'),15);assert.equal(await e('__arrowDebug.app.modal'),'reward-items');await shot('reward-items');await click('reward-close');assert.equal(await e('__arrowDebug.view.buttons.find(b=>b.id==="share-start").label'),'继续分享');await click('share-start');await until('__arrowDebug.app.modal==="share-reward"&&!__arrowDebug.app.sharePending');assert.deepEqual(await e('__arrowDebug.app.inventory'),{time:15,life:15,shuffle:15});assert.equal(await e('__arrowDebug.app.share.rescues'),0);await shot('share-claimed');await click('share-close');
 await e(`window.shareLog=[];window.origShare=__arrowDebug.app.platform.share;__arrowDebug.app.platform.share=()=>{shareLog.push('called');return origShare();};window.origAction=__arrowDebug.app.action;__arrowDebug.app.action=function(n){shareLog.push(n);return origAction.call(this,n);};__arrowDebug.fixture('tutorial');const a=__arrowDebug.app;a.lifeIntroDone=true;a.session.level.lifeLimit=3;a.session.lives=0;a.session.state='failed';a.session.failureReason='lives';a.events();__arrowDebug.render();`);
 assert.equal(await e('__arrowDebug.app.modal'),'life-rescue');await shot('share-life');assert.ok(await e('__arrowDebug.view.buttons.every(b=>b.y>=0&&b.y+b.height<=568)'));await click('share-life');await until('__arrowDebug.app.session.lives===3');assert.equal(await e('__arrowDebug.app.inventory.life'),15);
 await e(`(()=>{const a=__arrowDebug.app;a.session.level.timeLimitMs=120000;a.session.remainingMs=0;a.session.state='failed';a.session.failureReason='timeout';a.events();__arrowDebug.render();})();`);await shot('share-time');await click('share-time');await until('__arrowDebug.app.session.state==="playing"');assert.ok(await e('__arrowDebug.app.session.remainingMs>119000'));assert.equal(await e('__arrowDebug.app.share.rescues'),2);assert.equal(await e('__arrowDebug.app.inventory.time'),15);
 await c.send('Page.reload',{},s);await until('!!window.__arrowDebug');assert.equal(await e('__arrowDebug.app.share.rescues'),2);assert.equal(await e('__arrowDebug.app.share.rewardClaimed'),true);assert.equal(await e('__arrowDebug.app.inventory.time'),15);
 const captions=await e(`(()=>{const ctx=document.querySelector('canvas').getContext('2d'),original=ctx.fillText,drawn=[];ctx.fillText=function(value,...args){drawn.push(String(value));return original.call(this,value,...args);};try{__arrowDebug.render();}finally{ctx.fillText=original;}return drawn;})()`);
 for(const label of ['加时 × 15','容错 × 15','重排 × 15'])assert.ok(captions.includes(label),label);
 await shot('home-inventory-small');
 await c.send('Emulation.setDeviceMetricsOverride',{width:393,height:852,deviceScaleFactor:1,mobile:true},s);await delay(150);await e('__arrowDebug.render()');await shot('home-inventory-phone');
 }finally{await b.close();}
});
