'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Controller}=require('../src/ui/controller'),{Session}=require('../src/domain/session'),{fixtures}=require('../src/fixtures'),{fakePlatform,recordingContext}=require('./helpers.cjs'),{snapshot,restore,bindPersistence,encode,KEY}=require('../src/persistence/store');
function setup(){let time=Date.parse('2026-09-13T01:00:00Z'),calls=0;const p=fakePlatform(),data=new Map();p.now=()=>time;p.share=()=>calls++;p.storage={get:k=>data.get(k),set:(k,v)=>data.set(k,v)};const game=require('../src/runtime').mount(p);return {a:game.app,p,data,advance:ms=>time+=ms,returned:()=>{p.callbacks.hide();p.callbacks.show();if(game.app.modal==='reward-items'){assert.deepEqual(game.app.rewardPopup.items,{time:5,life:5,shuffle:5});game.app.action('reward-close');}},calls:()=>calls};}
function fail(a,kind){a.session=new Session({...fixtures.tutorial,number:3,lifeLimit:3,timeLimitMs:120000});a.currentLevel=3;a.screen='game';a.modal=null;a.lifeIntroDone=true;if(kind==='life'){a.session.lives=1;a.clickArrow('second');}else{a.session.remainingMs=1;a.tick(1);}}
test('P12 每日分享一次三种各5个，返回才发奖、重复返回不叠加、跨日重置且存档保留',()=>{
 const {a,p,data,advance,returned,calls}=setup();a.action('share');a.action('share-start');assert.equal(calls(),1);assert.equal(a.inventory.time,10);a.action('share-start');assert.equal(calls(),1);p.callbacks.show();assert.equal(a.inventory.time,10);returned();assert.deepEqual(a.inventory,{time:15,life:15,shuffle:15});returned();assert.equal(a.inventory.time,15);a.action('share-start');assert.equal(calls(),2);returned();assert.deepEqual(a.inventory,{time:15,life:15,shuffle:15});assert.equal(a.share.rescues,0);
 const b=new Controller(fakePlatform());restore(b,snapshot(a));assert.equal(b.share.rewardClaimed,true);assert.equal(b.inventory.life,15);
 advance(86400000);a.action('share-start');returned();assert.equal(a.inventory.time,20);assert.equal(a.share.rescues,0);assert.ok(data.get(KEY));
});
test('P12 时间与容错分享共用10次，不扣库存、各自恢复初始值，日奖励另计',()=>{
 const {a,returned,calls,advance}=setup();for(let i=0;i<10;i++){const kind=i%2?'life':'time';fail(a,kind);a.action('share-'+kind);returned();assert.equal(a.session.state,'playing');assert.equal(a.session.lives,3);assert.equal(a.session.remainingMs,kind==='time'?120000:120000);assert.equal(a.share.rescues,i+1);assert.equal(a.inventory[kind],10);assert.equal(a.session.recordEligible,false);}
 fail(a,'time');a.action('share-time');assert.equal(calls(),10);assert.equal(a.session.remainingMs,0);a.action('time-rescue-decline');a.action('home');a.action('share');a.action('share-start');returned();assert.equal(a.share.rescues,10);assert.equal(a.inventory.life,15);
 advance(86400000);a.action('share-close');fail(a,'life');a.action('share-life');returned();assert.equal(a.share.rescues,1);
});
test('P12 分享取消/异常不发奖，冻结原棋盘，无道具也可分享，竞速不能分享续关',()=>{
 const {a,p,returned}=setup();fail(a,'time');a.inventory.time=0;const before=JSON.stringify(a.session.level);a.action('share-time');a.tick(5000);assert.equal(a.session.remainingMs,0);a.action('share-cancel');returned();assert.equal(a.share.rescues,0);assert.equal(a.modal,'time-rescue');p.share=()=>{throw Error('unavailable')};a.action('share-time');assert.equal(a.modal,'time-rescue');assert.equal(a.inventory.time,0);p.share=()=>{};a.action('share-time');returned();assert.equal(a.session.remainingMs,120000);assert.equal(JSON.stringify(a.session.level),before);a.mode='race';assert.equal(require('../src/ui/time-rescue').eligible(a),false);
});
test('P12 使用道具重置对应项目，不累加、不改变另一项',()=>{
 const {a}=setup();fail(a,'time');a.session.lives=2;a.action('time-rescue-use');assert.equal(a.session.remainingMs,120000);assert.equal(a.session.lives,2);assert.equal(a.inventory.time,9);a.session.remainingMs=80000;a.action('item-life');assert.equal(a.session.lives,3);assert.equal(a.session.remainingMs,80000);assert.equal(a.inventory.life,9);
 const b=new Controller(fakePlatform());restore(b,snapshot(a));assert.equal(b.session.lives,3);assert.equal(b.session.remainingMs,80000);
});
test('P12 旧进度/普通纪录/竞速历史一次性清空，保留库存和设置，新进度不重置',()=>{
 const {a,p,data}=setup();const old=snapshot(a);old.campaignRevision=3;old.currentLevel=8;old.unlocked=9;old.inventory.life=27;old.settings.sound=false;old.levelBests={'3:1':1000};data.set(KEY,encode(old));data.set('arrow-garden.race-history.v1','[{"kind":"daily","elapsed":1,"period":"daily:2026-09-12"}]');const b=new Controller(p);bindPersistence(b,p.storage);assert.equal(b.unlocked,1);assert.deepEqual(b.levelBests,{});assert.equal(b.inventory.life,27);assert.equal(b.settings.sound,false);assert.equal(data.get('arrow-garden.race-history.v1'),'[]');b.unlocked=5;b.changed();const c=new Controller(p);bindPersistence(c,p.storage);assert.equal(c.unlocked,5);
});
test('P12 受阻600毫秒明显变色、突出阻挡且短震动，重复触摸不多扣',()=>{
 const {a,p}=setup();a.session=new Session({...fixtures.tutorial,number:3,lifeLimit:3});a.currentLevel=3;a.screen='game';a.lifeIntroDone=true;let feedback=0;p.feedback=()=>feedback++;a.clickArrow('second');assert.equal(a.session.lives,2);a.tick(500);a.clickArrow('second');assert.equal(a.session.lives,2);assert.equal(feedback,1);const {View}=require('../src/ui/view');const ctx=recordingContext(),v=new View(ctx);v.render(a,p.info());assert.ok(ctx.calls.some(c=>c[0]==='arc'));assert.equal(a.session.feedback.size,1);a.tick(101);assert.equal(a.session.feedback.size,0);a.clickArrow('second');assert.equal(a.session.lives,1);
});
test('P12 正式首页隐藏挑战、通关4解锁竞速，3关以普通5关为基准且递增',()=>{
 const {a,p}=setup(),v=new (require('../src/ui/view').View)(p.ctx);a.unlocked=20;v.render(a,p.info());assert.ok(!v.buttons.some(b=>b.id==='challenge'));a.action('challenge');assert.equal(a.mode,'campaign');a.unlocked=4;a.action('race');assert.equal(a.modal,'race-locked');a.action('race-close');a.session=new Session({...fixtures.boundary,number:4});a.currentLevel=4;a.screen='game';a.clickArrow('a');a.tick(1000);assert.equal(a.modal,'race-unlocked');assert.equal(a.unlocked,5);const {difficulty,ROUNDS}=require('../src/race/rules');assert.equal(ROUNDS,3);for(const kind of ['daily','weekly']){assert.equal(difficulty(1,kind).campaignLevel,5);assert.ok(difficulty(2,kind).minDepth>difficulty(1,kind).minDepth);assert.ok(difficulty(3,kind).minDepth>difficulty(2,kind).minDepth);}
});
test('P12 迁移保存失败显示错误，重试成功后才标记新版，不再清空后续进度',()=>{
 const {a,p,data}=setup(),old=snapshot(a);old.campaignRevision=3;old.unlocked=12;data.set(KEY,encode(old));let fail=true;const storage={get:k=>data.get(k),set:(k,v)=>{if(k===KEY&&fail)throw Error('disk');data.set(k,v);}};const b=new Controller(p);bindPersistence(b,storage);assert.equal(b.savedError,true);assert.equal(b.unlocked,1);fail=false;b.action('retry-save');assert.equal(b.savedError,false);assert.equal(require('../src/persistence/store').decode(data.get(KEY)).campaignRevision,4);b.unlocked=6;b.changed();const c=new Controller(p);bindPersistence(c,storage);assert.equal(c.unlocked,6);
});
test('P12 竞速分享领奖不使用道具，等待计入总时间，返回普通模式保留库存与额度',async()=>{
 const {a,advance,returned}=setup();a.unlocked=5;a.raceUnlockSeen=true;a.action('race');await a.action('race-daily');a.action('race-accept');a.action('share');a.action('share-start');advance(5000);returned();assert.equal(a.inventory.life,15);assert.equal(a.session.itemUses.life,0);assert.equal(require('../src/race/controller').elapsed(a),5000);a.action('share-close');a.action('pause');a.action('home');assert.equal(a.mode,'campaign');assert.equal(a.inventory.life,15);assert.equal(a.share.rewardClaimed,true);const b=new Controller(fakePlatform());restore(b,snapshot(a));assert.equal(b.inventory.life,15);assert.equal(b.share.rewardClaimed,true);
});
test('P12 微信菜单及主动分享接入，仅打开分享不假造发送成功',()=>{
 const {wx}=require('./helpers.cjs').fakeWx();let menu,handler,options;wx.showShareMenu=o=>menu=o;wx.onShareAppMessage=fn=>handler=fn;wx.shareAppMessage=o=>options=o;const p=require('../src/platform/wechat').createWechatPlatform(wx,{});assert.deepEqual(menu.menus,['shareAppMessage']);assert.ok(handler().title);p.share();assert.ok(options.title);assert.equal(options.query,'source=button');assert.equal(options.success,undefined);
});
