'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Session}=require('../src/domain/session'),{solve}=require('../src/generation/validate'),{Controller}=require('../src/ui/controller'),{fakePlatform}=require('./helpers.cjs'),{snapshot,restore,validate}=require('../src/persistence/store');
const board=key=>({number:8,width:6,height:6,lifeLimit:3,timeLimitMs:300000,obstacles:[],arrows:[{id:'key',path:[[1,1],[2,1]],direction:'right'},{id:'other',path:[[1,3],[2,3]],direction:'right'}],doors:[{id:'d',cell:[4,3],...(key?{keyArrowId:'key'}:{required:1})}]});
test('P18 数量门和钥匙门在箭头完全移出后打开，等待移动不扣机会',()=>{for(const key of [false,true]){const b=board(key),s=new Session(b);assert.ok(solve(b).valid);assert.equal(s.classify('other').type,'blocked');s.click('key');assert.equal(s.classify('other').type,'temporary');assert.equal(s.lives,3);s.tick(1000);assert.equal(s.classify('other').type,'allowed');assert.ok(s.drainEvents().some(e=>e.type==='door-opened'));s.click('other');s.tick(1000);assert.equal(s.state,'won');}});
test('P18 循环钥匙和过高开门数量不能通过可解性检查',()=>{for(const key of [false,true]){const b=board(key);if(key)b.doors[0].keyArrowId='other';else b.doors[0].required=2;assert.equal(solve(b).valid,false);}const b=board(true);b.doors[0].keyArrowId='missing';assert.equal(solve(b).valid,false);});
test('P18 重排保留已消除普通箭头计数及尚未解锁的钥匙门',async()=>{const {reshuffle}=require('../src/generation/reshuffle');for(const key of [false,true]){const b=board(key),s=new Session(b);const r=await reshuffle(s,()=>{throw Error('unexpected generator')},1);assert.ok(solve(r).valid);assert.equal(r.doors.length,1);assert.deepEqual(r.doors[0].cell,[1,2]);s.click('key');s.tick(1000);const opened=await reshuffle(s,null,2);assert.equal(opened.doors.length,0);assert.ok(solve(opened).valid);}});
test('P18 每日奖励独立于分享，每天一次、关闭重开不重复、隔日可领取',()=>{const p=fakePlatform();let now=Date.UTC(2026,8,13,4);p.now=()=>now;const a=new Controller(p);a.action('daily-reward');assert.deepEqual(a.inventory,{time:11,life:11,shuffle:11});assert.equal(a.modal,'reward-items');a.action('reward-close');a.action('daily-reward');assert.equal(a.inventory.time,11);const save=snapshot(a);assert.ok(validate(save));const b=new Controller(p);restore(b,save);b.action('daily-reward');assert.equal(b.inventory.time,11);now+=86400000;b.action('daily-reward');assert.equal(b.inventory.time,12);assert.equal(b.share.rewardClaimed,false);});
test('P18 存储故障时不给每日奖励，主页领取后按钮显示已领取',()=>{const p=fakePlatform(),a=new Controller(p),{View}=require('../src/ui/view'),v=new View(p.ctx);a.savedError=true;a.action('daily-reward');assert.equal(a.inventory.time,10);a.savedError=false;a.action('daily-reward');a.action('reward-close');v.render(a,p.info());assert.equal(v.buttons.find(b=>b.id==='daily-reward').label,'已领取');});

test('P18 开门状态与教学确认存档往返，重启本关恢复关闭的门',()=>{const a=new Controller(fakePlatform());a.session=new Session(board(true));a.currentLevel=8;a.lifeIntroDone=true;a.session.guideSeen=true;a.session.click('key');a.session.tick(1000);const data=snapshot(a);assert.ok(validate(data));const b=new Controller(fakePlatform());restore(b,data);assert.equal(b.session.guideSeen,true);assert.equal(b.session.classify('other').type,'allowed');assert.equal(b.session.restart().classify('other').type,'blocked');});

test('P18 全40个固定关卡按实际移动清空，所有门可打开且不扣错次数',()=>{for(const {id,board:b} of require('../config/campaign-levels.json')){const s=new Session(b),sequence=solve(b).sequence;for(const arrow of sequence){assert.equal(s.click(arrow).type,'allowed','第'+id+'关 '+arrow);let frames=0;while(s.moves.size&&s.state==='playing'&&frames++<1000)s.tick(16);assert.equal(s.moves.size,0);assert.notEqual(s.state,'failed');}assert.equal(s.state,'won');assert.equal(s.lives,b.lifeLimit);for(const door of b.doors||[])assert.ok(require('../src/domain/doors').isOpen(door,b,s.removed));}});
