'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Session}=require('../src/domain/session'),{solve}=require('../src/generation/validate'),{validateLevel}=require('../src/domain/board');
function board(key){return {number:8,width:8,height:8,lifeLimit:3,timeLimitMs:300000,arrows:[{id:'outer',path:[[7,1],[7,0]],direction:'up'},{id:'key',path:[[3,1],[4,1],[5,1],[6,1]],direction:'right'},...[1,2,3,4].map(x=>({id:'inner'+x,path:[[x,3],[x,4]],direction:'down'}))],obstacles:[],doors:[{id:'gate',edges:Array.from({length:8},(_,x)=>[[x,7],[x,8]]),...(key?{keyArrowId:'key'}:{required:2})}]};}
test('P19 整段闸门封住4条出口，外侧解谜完成才打开；动画结束后保持畅通',()=>{for(const key of [false,true]){const b=board(key),s=new Session(b);assert.ok(solve(b).valid);for(const x of [1,2,3,4])assert.equal(s.classify('inner'+x).type,'blocked');assert.equal(s.classify('key').type,'blocked');s.click('outer');s.tick(1000);s.click('key');assert.equal(s.classify('inner1').type,'temporary');s.tick(1000);assert.equal(s.doorEffects.size,1);for(const x of [1,2,3,4])assert.equal(s.classify('inner'+x).type,'allowed');s.pause();s.tick(2000);assert.equal(s.doorEffects.size,1);s.resume();s.tick(901);assert.equal(s.doorEffects.size,0);assert.equal(s.lives,3);}});
test('P19 非相邻、内部穿过身体、重叠边界的闸门拒绝配置',()=>{for(const edge of [[ [0,0],[2,0] ],[[1,1],[2,1]],[[20,20],[20,21]]]){const b=board(false);b.doors[0].edges=[edge];assert.equal(validateLevel(b).valid,false);}const b=board(false);b.doors.push({...b.doors[0],id:'duplicate'});assert.equal(validateLevel(b).valid,false);});
test('P19 闸门与钥匙关系重排、保存、恢复、重试均正确',async()=>{const {reshuffle}=require('../src/generation/reshuffle'),{snapshot,restore,validate}=require('../src/persistence/store'),{Controller}=require('../src/ui/controller'),{fakePlatform}=require('./helpers.cjs');const a=new Controller(fakePlatform());a.currentLevel=8;a.lifeIntroDone=true;a.session=new Session(board(true));const changed=await reshuffle(a.session,null,1);assert.ok(solve(changed).valid);assert.deepEqual(changed.doors[0].edges[0],[[7,0],[7,-1]]);a.session=new Session(changed);a.session.click('outer');a.session.tick(1000);const data=snapshot(a);assert.ok(validate(data));const b=new Controller(fakePlatform());restore(b,data);assert.equal(b.session.classify('key').type,'allowed');assert.equal(b.session.classify('inner1').type,'blocked');assert.equal(b.session.restart().classify('key').type,'blocked');});

test('P19 正式关卡每扇闸门至少覆盖5条箭头出口，钥匙必须先解开遮挡',()=>{const {block}=require('../src/domain/doors'),{firstBlocker}=require('../src/domain/board');for(const {id,board:b}of require('../config/campaign-levels.json')){if(id<8)continue;assert.ok(b.doors.length);for(const d of b.doors){assert.ok(d.edges.length>=6);const map=new Map();block(d,map);assert.ok(b.arrows.filter(a=>firstBlocker(a,b,map)).length>=5,'第'+id+'关闸门影响不足');if(d.keyArrowId)assert.equal(new Session(b).classify(d.keyArrowId).type,'blocked');else assert.ok(d.required>=5);}assert.ok(solve(b).valid);}});

test('P19 边界闸门不占格，不减少箭头长度统计',()=>{const b=board(false),m=solve(b).metrics,total=b.arrows.reduce((n,a)=>n+a.path.length,0);assert.equal(m.averageLength,total/b.arrows.length);assert.equal(m.fill,total/(b.width*b.height));});
