'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Controller}=require('../src/ui/controller'),{Session}=require('../src/domain/session'),{fixtures}=require('../src/fixtures'),{fakePlatform}=require('./helpers.cjs'),{View}=require('../src/ui/view');
function app(){const a=new Controller(fakePlatform());a.session=new Session({...fixtures.tutorial,number:3,lifeLimit:3});a.currentLevel=3;a.lifeIntroDone=true;a.screen='game';return a;}
test('P21 提示仅标记当前可移出的箭头，扣一个旧库存且不改布局时间生命',()=>{const a=app(),s=a.session,before=JSON.stringify(s.level),allowed=s.level.arrows.filter(x=>s.classify(x.id).type==='allowed').map(x=>x.id);a.action('item-shuffle');assert.equal(s.hintIds.length,1);assert.ok(allowed.includes(s.hintIds[0]));assert.ok(!s.hintIds.includes('second'));assert.equal(a.inventory.shuffle,9);assert.equal(s.itemUses.shuffle,1);assert.equal(JSON.stringify(s.level),before);assert.equal(s.lives,3);assert.equal(s.remainingMs,null);const v=new View(a.platform.ctx);v.render(a,a.platform.info());assert.equal(a.modal,null);a.action('item-shuffle');assert.equal(a.inventory.shuffle,9);s.pause();a.tick(6000);assert.ok(s.hintUntil>s.time);s.resume();a.tick(5001);assert.ok(s.hintUntil<s.time);});
test('P21 点击提示箭头结束高亮，菜单使用返回棋盘，空库存不发提示',()=>{const a=app();a.action('items');a.action('item-shuffle');assert.equal(a.modal,null);assert.equal(a.session.state,'playing');a.clickArrow(a.session.hintIds[0]);assert.equal(a.session.hintUntil,0);const b=app();b.inventory.shuffle=0;b.action('item-shuffle');assert.equal(b.modal,'item-empty');assert.equal(b.session.hintUntil,undefined);});
test('P21 无可用箭头、移动中不扣提示道具，竞速可使用',()=>{const a=app();for(const x of a.session.level.arrows)a.session.feedback.set(x.id,{until:1000});a.action('item-shuffle');assert.equal(a.inventory.shuffle,10);const b=app();b.clickArrow('first');b.action('item-shuffle');assert.equal(b.inventory.shuffle,10);const c=app();c.mode='race';c.action('item-shuffle');assert.equal(c.inventory.shuffle,9);assert.equal(c.session.hintIds.length,1);});
test('P21 旧库存和奖励沿用为提示，页面及说明显示提示名称',()=>{const a=app(),{snapshot,restore}=require('../src/persistence/store');a.inventory.shuffle=27;const b=new Controller(fakePlatform());restore(b,snapshot(a));assert.equal(b.inventory.shuffle,27);b.screen='home';b.modal=null;b.action('home-info-shuffle');const v=new View(b.platform.ctx);v.render(b,b.platform.info());assert.ok(b.platform.ctx.calls.some(c=>c[0]==='fillText'&&c[1]==='提示道具'));assert.ok(require('../src/campaign/catalog').rewardText(3).includes('提示道具'));});
test('P21 随机提示覆盖候选首尾且每次只有一条',()=>{const random=Math.random;try{for(const value of [0,.999999]){Math.random=()=>value;const a=app(),ids=a.session.level.arrows.filter(x=>a.session.classify(x.id).type==='allowed').map(x=>x.id);assert.ok(ids.length>1);a.action('item-shuffle');assert.deepEqual(a.session.hintIds,[ids[value===0?0:ids.length-1]]);}}finally{Math.random=random;}});
test('P21 四侧闸门及标牌都在棋盘格外，箭头仍按原格坐标绘制',()=>{const {drawBoard}=require('../src/rendering/board');for(const side of ['top','bottom','left','right']){const p=fakePlatform(),level={...fixtures.tutorial};level.doors=[{id:'gate',required:1,edges:Array.from({length:6},(_,i)=>side==='top'?[[i,0],[i,-1]]:side==='bottom'?[[i,5],[i,6]]:side==='left'?[[0,i],[-1,i]]:[[5,i],[6,i]])}];const t=drawBoard(p.ctx,level,{x:30,y:40,width:240,height:240});const badge=p.ctx.calls.find(c=>c[0]==='fillRect'&&c[3]===24&&c[4]===20);assert.ok(badge);const [,x,y,w,h]=badge;assert.ok(x+w<=t.x||x>=t.x+t.width||y+h<=t.y||y>=t.y+t.height,side);}});
test('P21 日周竞速只显示提示入口，使用仍计时，空库存可关闭并继续',async()=>{for(const kind of ['daily','weekly']){const a=app();let now=Date.UTC(2026,8,14,8);a.platform.now=()=>now;a.screen='home';a.session=null;a.unlocked=5;a.raceGenerate=async()=>Array.from({length:3},()=>({...fixtures.tutorial,timeLimitMs:null}));a.action('race');await a.action('race-'+kind);a.action('race-accept');const v=new View(a.platform.ctx);v.render(a,a.platform.info());assert.deepEqual(v.buttons.filter(b=>b.id.startsWith('item-')).map(b=>b.id),['item-shuffle']);const rect=v.buttons.find(b=>b.id==='item-shuffle');assert.equal(v.hitButton(rect.x+rect.width/2,rect.y+rect.height/2),'item-shuffle');a.action('item-shuffle');assert.equal(a.inventory.shuffle,9);assert.equal(a.session.hintIds.length,1);now+=1000;assert.equal(require('../src/race/controller').elapsed(a),1000);a.action('item-time');a.action('item-life');assert.equal(a.inventory.time,10);assert.equal(a.inventory.life,10);a.inventory.shuffle=0;a.action('item-shuffle');assert.equal(a.modal,'item-empty');now+=2000;a.action('item-empty-close');assert.equal(a.modal,null);assert.equal(a.session.state,'playing');assert.equal(require('../src/race/controller').elapsed(a),3000);a.action('pause');a.action('home');assert.equal(a.inventory.shuffle,0);assert.equal(a.mode,'campaign');}});
