'use strict';
const test = require('node:test'), assert = require('node:assert/strict');
const { Session } = require('../src/domain/session'), { fixtures } = require('../src/fixtures');
const { Controller } = require('../src/ui/controller');
const { fakePlatform, fakeWx } = require('./helpers.cjs');
const { snapshot, restore, createStore, bindPersistence, KEY, BACKUP, encode } = require('../src/persistence/store');
function app(level = fixtures.tutorial) { const a = new Controller(fakePlatform()); a.session = new Session(level); a.currentLevel = level.number; a.screen = 'game'; return a; }
function memory() { const data = new Map(); return { data, get: k => data.get(k), set: (k, v) => data.set(k, v) }; }
test('P5 动画中快照完成已接受移动，前台仍按动画计数', () => { const a = app(); a.session.click('first'); a.session.tick(20); const saved = snapshot(a); assert.equal(a.session.remaining, 3); assert.deepEqual(saved.session.removed, ['first']); const b = app(); restore(b, saved); assert.equal(b.session.remaining, 2); assert.equal(b.session.moves.size, 0); });
test('P5 多箭头同时中断恢复完整稳定状态', () => { const a = app(); a.session.click('first'); a.session.click('third'); const b = app(); restore(b, snapshot(a)); assert.equal(b.session.remaining, 1); assert.deepEqual([...b.session.removed], ['first', 'third']); });
test('P5 最后一条动画中断恢复通关且只解锁下一关', () => { const a = app(fixtures.boundary); a.session.click('a'); const saved = snapshot(a); assert.equal(saved.session.state, 'won'); assert.equal(saved.unlocked, 2); const b = app(); restore(b, saved); assert.equal(b.session.state, 'won'); });
test('P5 扣命、失败与移动并行中断不恢复生命或变成通关', () => { const a = app({ ...fixtures.tutorial, number: 21, lifeLimit: 1 }); a.session.click('third'); a.session.click('second'); const b = app(); restore(b, snapshot(a)); assert.equal(b.session.lives, 0); assert.equal(b.session.state, 'failed'); assert.equal(b.session.remaining, 2); });
test('P5 原始布局完整保存，版本变化不影响重试', () => { const a = app(); a.session.level.generatorVersion = 999; a.session.click('first'); const b = app(); restore(b, snapshot(a)); assert.deepEqual(b.session.restart().level, a.session.level); assert.equal(b.session.restart().remaining, 3); });
test('P5 读写、设置、教学标记持久化', () => { const storage = memory(), a = app(); bindPersistence(a, storage); a.settings.sound = false; a.tutorialDone = true; a.lifeIntroDone = true; a.changed(); const b = new Controller(fakePlatform()); bindPersistence(b, storage); assert.equal(b.settings.sound, false); assert.equal(b.tutorialDone, true); assert.equal(b.lifeIntroDone, true); assert.deepEqual(b.session.level, a.session.level); });
test('P5 主存档损坏使用备份，双份损坏保守恢复原关卡', () => { const storage = memory(), store = createStore(storage), a = app(); a.session.click('first'); store.save(snapshot(a)); storage.set(KEY, 'broken'); assert.equal(store.load().recovered, true); assert.equal(store.load().data.session.removed.length, 1); const damaged = JSON.stringify({ payload: JSON.stringify(snapshot(a)), checksum: 'wrong' }); storage.set(KEY, damaged); storage.set(BACKUP, damaged); const recovered = store.load(); assert.equal(recovered.data.session.removed.length, 0); assert.equal(recovered.data.session.state, 'playing'); });
test('P5 非法ID、生命、重复消除、错误终态拒绝保存', () => { for (const mutate of [s => s.removed = ['missing'], s => s.removed = ['first', 'first'], s => s.lives = 99, s => s.state = 'won']) {
    const data = snapshot(app());
    mutate(data.session);
    assert.throws(() => createStore(memory()).save(data), /invalid snapshot/);
} });
test('P5 保存失败可见，重试成功才清除错误', () => { let broken = true; const storage = { get: () => null, set() { if (broken)
        throw new Error('disk full'); } }; const a = app(); bindPersistence(a, storage); a.changed(); assert.equal(a.savedError, true); broken = false; a.action('retry-save'); assert.equal(a.savedError, false); });
test('P5 前后台生命周期停止声音且完成移动，显示后不会补算后台时间', () => { const { mount } = require('../src/runtime'); const p = fakePlatform(); p.storage = memory(); let stopped = 0; p.stopFeedback = () => stopped++; const g = mount(p); g.app.session = new Session(fixtures.tutorial); g.app.screen = 'game'; g.app.session.click('first'); p.callbacks.hide(); assert.equal(stopped, 1); assert.equal(g.app.session.moves.size, 0); assert.equal(g.app.session.remaining, 2); assert.equal(g.app.session.state, 'paused'); p.callbacks.show(); assert.equal(g.app.session.state, 'playing'); g.stop(); });
test('P5 音效关闭不创建音源，重复播放复用，能力失败不影响规则', () => { const { createFeedback } = require('../src/platform/feedback'); let made = 0, played = 0, vibrated = 0; const f = createFeedback(() => { made++; return { play() { played++; }, stop() { } }; }, () => vibrated++); f.play('removed', { sound: false, vibration: false }); assert.equal(made, 0); for (let i = 0; i < 10; i++)
    f.play('removed', { sound: true, vibration: true }); assert.equal(made, 1); assert.equal(played, 10); assert.equal(vibrated, 10); assert.doesNotThrow(() => createFeedback(() => { throw Error('unsupported'); }, () => { throw Error('unsupported'); }).play('removed', { sound: true, vibration: true })); });
test('P5 生成的音频是有有效采样的PCM WAV', () => { const { wav } = require('../scripts/audio.cjs'); const b = wav([440], .1); assert.equal(b.toString('ascii', 0, 4), 'RIFF'); assert.equal(b.readUInt32LE(40), 4410); assert.ok(b.subarray(44).some(x => x !== 0)); });
test('P5 读取暂时失败时不得覆盖旧存档，重试后恢复', () => { const saved = memory(), original = app({ ...fixtures.tutorial, number: 21, lifeLimit: 3 }); original.session.click('second'); createStore(saved).save(snapshot(original)); let broken = true, writes = 0; const storage = { get(k) { if (broken)
        throw new Error('temporarily unavailable'); return saved.get(k); }, set(k, v) { writes++; saved.set(k, v); } }; const a = new Controller(fakePlatform()); bindPersistence(a, storage); a.changed(); assert.equal(writes, 0); assert.equal(a.savedError, true); broken = false; a.action('retry-save'); assert.equal(a.savedError, false); assert.equal(a.session.lives, 2); assert.equal(a.currentLevel, 21); });
